package com.maxisch.dungeon

import net.minecraft.core.registries.BuiltInRegistries
import net.minecraft.tags.FluidTags
import net.minecraft.world.level.block.SlabBlock
import net.minecraft.world.level.block.state.BlockState

/**
 * Pre-flattening block ids for the blocks a Catacombs room can be built out of.
 *
 * Room identification hashes a column of ids (see [WorldProbe.coreHash]), and the hashes in
 * `rooms.json` were produced on 1.8 block ids. Any deviation from this table - a different id, a
 * missing entry, a different state suffix - changes the hash and the room stops being recognised,
 * so this mirrors NoammAddons' table exactly rather than trying to be clever.
 */
object LegacyBlockIds {

    private val BLOCKS = mapOf(
        "minecraft:air" to 0,
        "minecraft:stone" to 1,
        "minecraft:polished_andesite" to 1,
        "minecraft:polished_diorite" to 1,
        "minecraft:polished_granite" to 1,
        "minecraft:andesite" to 1,
        "minecraft:diorite" to 1,
        "minecraft:granite" to 1,
        "minecraft:grass_block" to 2,
        "minecraft:coarse_dirt" to 3,
        "minecraft:dirt" to 3,
        "minecraft:cobblestone" to 4,
        "minecraft:dark_oak_planks" to 5,
        "minecraft:spruce_planks" to 5,
        "minecraft:jungle_planks" to 5,
        "minecraft:birch_planks" to 5,
        "minecraft:bedrock" to 7,
        "minecraft:lava" to 11,
        "minecraft:gravel" to 13,
        "minecraft:gold_ore" to 14,
        "minecraft:oak_wood" to 17,
        "minecraft:oak_log" to 17,
        "minecraft:oak_leaves" to 18,
        "minecraft:lapis_block" to 22,
        "minecraft:sandstone" to 24,
        "minecraft:sticky_piston" to 29,
        "minecraft:cobweb" to 30,
        "minecraft:piston" to 33,
        "minecraft:piston_head" to 34,
        "minecraft:gray_wool" to 35,
        "minecraft:red_wool" to 35,
        "minecraft:black_wool" to 35,
        "minecraft:light_gray_wool" to 35,
        "minecraft:green_wool" to 35,
        "minecraft:orange_wool" to 35,
        "minecraft:brown_mushroom" to 39,
        "minecraft:gold_block" to 41,
        "minecraft:iron_block" to 42,
        "minecraft:smooth_stone" to 43,
        "minecraft:smooth_sandstone" to 43,
        "minecraft:cobblestone_slab[type=double]" to 43,
        "minecraft:stone_brick_slab[type=double]" to 43,
        "minecraft:smooth_stone_slab[type=double]" to 43,
        "minecraft:sandstone_slab[type=double]" to 43,
        "minecraft:stone_brick_slab[type=top]" to 44,
        "minecraft:stone_brick_slab[type=bottom]" to 44,
        "minecraft:cobblestone_slab[type=top]" to 44,
        "minecraft:cobblestone_slab[type=bottom]" to 44,
        "minecraft:smooth_stone_slab[type=top]" to 44,
        "minecraft:smooth_stone_slab[type=bottom]" to 44,
        "minecraft:sandstone_slab[type=top]" to 44,
        "minecraft:sandstone_slab[type=bottom]" to 44,
        "minecraft:bookshelf" to 47,
        "minecraft:mossy_cobblestone" to 48,
        "minecraft:obsidian" to 49,
        "minecraft:wall_torch" to 50,
        "minecraft:torch" to 50,
        "minecraft:fire" to 51,
        "minecraft:chest" to 54,
        "minecraft:diamond_block" to 57,
        "minecraft:ladder" to 65,
        "minecraft:rail" to 66,
        "minecraft:cobblestone_stairs" to 67,
        "minecraft:lever" to 69,
        "minecraft:stone_button" to 77,
        "minecraft:ice" to 79,
        "minecraft:oak_fence" to 85,
        "minecraft:glowstone" to 89,
        "minecraft:black_stained_glass" to 95,
        "minecraft:light_gray_stained_glass" to 95,
        "minecraft:infested_cobblestone" to 97,
        "minecraft:stone_bricks" to 98,
        "minecraft:mossy_stone_bricks" to 98,
        "minecraft:cracked_stone_bricks" to 98,
        "minecraft:chiseled_stone_bricks" to 98,
        "minecraft:brown_mushroom_block" to 99,
        "minecraft:iron_bars" to 101,
        "minecraft:vine" to 106,
        "minecraft:stone_brick_stairs" to 109,
        "minecraft:nether_bricks" to 112,
        "minecraft:cauldron" to 118,
        "minecraft:end_portal_frame" to 120,
        "minecraft:end_stone" to 121,
        "minecraft:spruce_slab[type=double]" to 125,
        "minecraft:oak_slab[type=double]" to 125,
        "minecraft:dark_oak_slab[type=double]" to 125,
        "minecraft:spruce_slab[type=top]" to 126,
        "minecraft:spruce_slab[type=bottom]" to 126,
        "minecraft:oak_slab[type=top]" to 126,
        "minecraft:oak_slab[type=bottom]" to 126,
        "minecraft:dark_oak_slab[type=top]" to 126,
        "minecraft:dark_oak_slab[type=bottom]" to 126,
        "minecraft:emerald_block" to 133,
        "minecraft:spruce_stairs" to 134,
        "minecraft:cobblestone_wall" to 139,
        "minecraft:redstone_block" to 152,
        "minecraft:hopper" to 154,
        "minecraft:quartz_block" to 155,
        "minecraft:quartz_stairs" to 156,
        "minecraft:cyan_terracotta" to 159,
        "minecraft:blue_terracotta" to 159,
        "minecraft:light_blue_terracotta" to 159,
        "minecraft:gray_terracotta" to 159,
        "minecraft:light_gray_terracotta" to 159,
        "minecraft:lime_terracotta" to 159,
        "minecraft:green_terracotta" to 159,
        "minecraft:black_terracotta" to 159,
        "minecraft:magenta_terracotta" to 159,
        "minecraft:purple_terracotta" to 159,
        "minecraft:red_terracotta" to 159,
        "minecraft:white_terracotta" to 159,
        "minecraft:orange_terracotta" to 159,
        "minecraft:yellow_terracotta" to 159,
        "minecraft:pink_terracotta" to 159,
        "minecraft:brown_terracotta" to 159,
        "minecraft:magenta_stained_glass_pane" to 160,
        "minecraft:dark_oak_stairs" to 164,
        "minecraft:slime_block" to 165,
        "minecraft:barrier" to 166,
        "minecraft:dark_prismarine" to 168,
        "minecraft:prismarine" to 168,
        "minecraft:prismarine_bricks" to 168,
        "minecraft:sea_lantern" to 169,
        "minecraft:green_carpet" to 171,
        "minecraft:gray_carpet" to 171,
        "minecraft:light_gray_carpet" to 171,
        "minecraft:red_carpet" to 171,
        "minecraft:brown_carpet" to 171,
        "minecraft:magenta_carpet" to 171,
        "minecraft:blue_carpet" to 171,
        "minecraft:light_blue_carpet" to 171,
        "minecraft:white_carpet" to 171,
        "minecraft:orange_carpet" to 171,
        "minecraft:yellow_carpet" to 171,
        "minecraft:lime_carpet" to 171,
        "minecraft:pink_carpet" to 171,
        "minecraft:cyan_carpet" to 171,
        "minecraft:purple_carpet" to 171,
        "minecraft:black_carpet" to 171,
        "minecraft:coal_block" to 173,
        "minecraft:packed_ice" to 174,
        "minecraft:sunflower" to 175,
        "minecraft:red_sandstone_slab[type=double]" to 181,
        "minecraft:red_sandstone_slab[type=top]" to 182,
        "minecraft:red_sandstone_slab[type=bottom]" to 182,
        "minecraft:spruce_fence" to 188,
    )

    /** Null for anything outside the table; the caller skips those blocks entirely. */
    fun idOf(state: BlockState): Int? {
        val fluid = state.fluidState
        if (!fluid.isEmpty) {
            if (fluid.`is`(FluidTags.WATER)) return if (fluid.isSource) 9 else 8
            if (fluid.`is`(FluidTags.LAVA)) return if (fluid.isSource) 11 else 10
        }

        var name = BuiltInRegistries.BLOCK.getKey(state.block).toString()
        if (state.block is SlabBlock) {
            name += "[type=${state.getValue(SlabBlock.TYPE).name.lowercase()}]"
        }
        return BLOCKS[name]
    }
}
